# Generated by Django 4.2.2 on 2025-03-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
    ]
